#!/usr/bin/env node
/**
 * build-tokens.mjs
 *
 * Reads the canonical SCSS token partials and generates a JS module
 * (`lib/designTokens.js`) that exports the same values as plain objects.
 *
 * This bridges the gap during migration: components that currently import
 * from `lib/design-tokens.ts` can be pointed at `lib/designTokens.js`
 * once they no longer need TypeScript types.
 *
 * Usage: node scripts/build-tokens.mjs
 *        npm run build:tokens
 */

import { readFileSync, writeFileSync } from "fs"
import { resolve, dirname } from "path"
import { fileURLToPath } from "url"

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, "..")

// ── Parse SCSS variables from a file ──
function parseSCSSVars(filePath) {
  const content = readFileSync(resolve(ROOT, filePath), "utf-8")
  const vars = {}
  const re = /^\$([a-zA-Z0-9_-]+):\s*([^;]+);/gm
  let match
  while ((match = re.exec(content)) !== null) {
    const name = match[1].trim()
    let value = match[2].trim()
    // Skip map/list values and @use references
    if (value.startsWith("(") || value.includes("map-get") || value.includes("@")) continue
    vars[name] = value
  }
  return vars
}

// ── Convert SCSS var name to JS camelCase ──
function toCamelCase(str) {
  return str.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase())
}

// ── Build color groups ──
function buildColorScale(vars, prefix) {
  const scale = {}
  for (const [key, value] of Object.entries(vars)) {
    if (key.startsWith(prefix)) {
      const step = key.replace(prefix + "-", "")
      scale[step] = value
    }
  }
  return scale
}

// ── Main ──
const colors = parseSCSSVars("src/design-system/tokens/_colors.scss")
const typography = parseSCSSVars("src/design-system/tokens/_typography.scss")
const spacing = parseSCSSVars("src/design-system/tokens/_spacing.scss")
const radii = parseSCSSVars("src/design-system/tokens/_radii.scss")
const motion = parseSCSSVars("src/design-system/tokens/_motion.scss")
const zIndex = parseSCSSVars("src/design-system/tokens/_z-index.scss")
const breakpoints = parseSCSSVars("src/design-system/tokens/_breakpoints.scss")

const output = `// ─────────────────────────────────────────────────────────────────────────────
// AUTO-GENERATED — Do not edit manually.
// Source: src/design-system/tokens/*.scss
// Generated by: scripts/build-tokens.mjs
// Run: npm run build:tokens
// ─────────────────────────────────────────────────────────────────────────────

export const colors = {
  blue:    ${JSON.stringify(buildColorScale(colors, "tp-blue"), null, 4)},
  violet:  ${JSON.stringify(buildColorScale(colors, "tp-violet"), null, 4)},
  amber:   ${JSON.stringify(buildColorScale(colors, "tp-amber"), null, 4)},
  slate:   ${JSON.stringify(buildColorScale(colors, "tp-slate"), null, 4)},
  success: ${JSON.stringify(buildColorScale(colors, "tp-success"), null, 4)},
  warning: ${JSON.stringify(buildColorScale(colors, "tp-warning"), null, 4)},
  error:   ${JSON.stringify(buildColorScale(colors, "tp-error"), null, 4)},
  ai: {
    pink:   ${JSON.stringify(colors["ai-pink"])},
    violet: ${JSON.stringify(colors["ai-violet"])},
    indigo: ${JSON.stringify(colors["ai-indigo"])},
  },
}

export const semanticColors = {
  background:             ${JSON.stringify(colors["background"] || colors["tp-slate-100"])},
  foreground:             ${JSON.stringify(colors["foreground"] || colors["tp-slate-900"])},
  card:                   ${JSON.stringify(colors["card"] || colors["tp-slate-0"])},
  cardForeground:         ${JSON.stringify(colors["card-foreground"] || colors["tp-slate-900"])},
  primary:                ${JSON.stringify(colors["primary"] || colors["tp-blue-500"])},
  primaryForeground:      ${JSON.stringify(colors["primary-foreground"] || colors["tp-slate-0"])},
  secondary:              ${JSON.stringify(colors["secondary"] || colors["tp-violet-500"])},
  secondaryForeground:    ${JSON.stringify(colors["secondary-foreground"] || colors["tp-slate-0"])},
  muted:                  ${JSON.stringify(colors["muted"] || colors["tp-slate-100"])},
  mutedForeground:        ${JSON.stringify(colors["muted-foreground"] || colors["tp-slate-500"])},
  destructive:            ${JSON.stringify(colors["destructive"] || "#C8102E")},
  destructiveForeground:  ${JSON.stringify(colors["destructive-foreground"] || colors["tp-slate-0"])},
  border:                 ${JSON.stringify(colors["border"] || colors["tp-slate-200"])},
  input:                  ${JSON.stringify(colors["input"] || colors["tp-slate-200"])},
  ring:                   ${JSON.stringify(colors["ring"] || colors["tp-blue-500"])},
}

export const typography = {
  fontHeading: ${JSON.stringify(typography["font-heading"] || "'Mulish', var(--font-heading), sans-serif")},
  fontBody:    ${JSON.stringify(typography["font-body"] || "'Inter', var(--font-sans), sans-serif")},
  fontMono:    ${JSON.stringify(typography["font-mono"] || "ui-monospace, 'SF Mono', SFMono-Regular, Menlo, Consolas, 'Liberation Mono', monospace")},
}

export const spacing = {
  base: 8,
}

export const radii = {
${Object.entries(radii).map(([k, v]) => `  ${toCamelCase(k)}: ${JSON.stringify(v)},`).join("\n")}
}

export const zIndex = {
${Object.entries(zIndex).map(([k, v]) => `  ${toCamelCase(k)}: ${v},`).join("\n")}
}

export const breakpoints = {
${Object.entries(breakpoints).filter(([k]) => k.startsWith("breakpoint-")).map(([k, v]) => `  ${k.replace("breakpoint-", "")}: ${JSON.stringify(v)},`).join("\n")}
}
`

const outPath = resolve(ROOT, "lib/designTokens.js")
writeFileSync(outPath, output, "utf-8")
console.log(`✅ Generated ${outPath}`)
